version: "3"

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=jacobian.org
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    env_file: [".env"]
    command: waitress-serve --listen=*:8000 config.wsgi:application
    ports: ["8000:8000"]
    depends_on: ["db"]
    environment:
      - DATABASE_URL=postgres://postgres@db/jacobian.org
      - PYTHONDONTWRITEBYTECODE=true
    volumes:
      - .:/code

volumes:
  postgres_data:
