# Generated by Django 2.1.3 on 2018-11-14 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181031_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmark',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
