# Generated by Django 3.0.1 on 2020-02-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_new_photo_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
