# Generated by Django 2.1.3 on 2018-11-15 22:37

from django.db import migrations, models
import django.db.models.deletion
import django_postgres_unlimited_varchar


class Migration(migrations.Migration):

    dependencies = [("speaking_portfolio", "0003_auto_20181112_1542")]

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", django_postgres_unlimited_varchar.UnlimitedCharField()),
                ("link", models.URLField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="presentation",
            name="conference",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentations",
                to="speaking_portfolio.Conference",
            ),
        ),
    ]
