# Generated by Django 2.1.3 on 2018-11-15 22:37

from django.db import migrations


def move_conference_data_to_conference_model(apps, schema_editor):
    Conference = apps.get_model("speaking_portfolio", "Conference")
    Presentation = apps.get_model("speaking_portfolio", "Presentation")
    for p in Presentation.objects.all():
        p.conference, created = Conference.objects.get_or_create(
            title=p.conference_title, defaults={"link": p.conference_link}
        )
        p.save()


class Migration(migrations.Migration):
    dependencies = [("speaking_portfolio", "0004_create_conference_model")]
    operations = [migrations.RunPython(move_conference_data_to_conference_model)]
