# Generated by Django 2.1.3 on 2018-11-15 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("speaking_portfolio", "0005_move_conference_data_to_conference_model")
    ]

    operations = [
        migrations.RemoveField(model_name="presentation", name="conference_link"),
        migrations.RemoveField(model_name="presentation", name="conference_title"),
        migrations.AlterField(
            model_name="presentation",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentations",
                to="speaking_portfolio.Conference",
            ),
        ),
    ]
