# Generated by Django 2.1.3 on 2018-11-16 00:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_postgres_unlimited_varchar


class Migration(migrations.Migration):

    dependencies = [
        ("speaking_portfolio", "0006_drop_conference_fields_from_presentation")
    ]

    operations = [
        migrations.CreateModel(
            name="Coverage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    django_postgres_unlimited_varchar.UnlimitedCharField(
                        choices=[
                            ("video", "Video"),
                            ("slides", "Slides"),
                            ("link", "Link"),
                            ("notes", "Notes"),
                            ("write-up", "Write-Up"),
                        ]
                    ),
                ),
                ("url", models.URLField()),
                (
                    "oembed",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage",
                        to="speaking_portfolio.Presentation",
                    ),
                ),
            ],
            options={"verbose_name_plural": "coverage"},
        )
    ]
