# Generated by Django 2.1.3 on 2018-11-16 00:26

from django.db import migrations


def migrate_coverage_to_model(apps, schema_editor):
    Presentation = apps.get_model("speaking_portfolio", "Presentation")

    for p in Presentation.objects.all():
        if p.video_link:
            p.coverage.create(type="video", url=p.video_link)
        if p.slides_link:
            p.coverage.create(type="slides", url=p.slides_link)
        if p.text_link:
            p.coverage.create(type="write-up", url=p.text_link)


class Migration(migrations.Migration):
    dependencies = [("speaking_portfolio", "0007_add_coverage_model")]
    operations = [migrations.RunPython(migrate_coverage_to_model)]
