# Generated by Django 2.1.3 on 2018-11-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("speaking_portfolio", "0008_migrate_coverage_to_model")]

    operations = [
        migrations.RemoveField(model_name="presentation", name="slides_link"),
        migrations.RemoveField(model_name="presentation", name="text_link"),
        migrations.RemoveField(model_name="presentation", name="video_link"),
    ]
