# Adapted from https://github.com/GoogleCloudPlatform/django-demo-app-unicodex/blob/master/.cloudbuild/build-migrate-deploy.yaml

steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args: [build, -t, gcr.io/$PROJECT_ID/jacobiandotorg, .]

  - id: push
    name: gcr.io/cloud-builders/docker
    args: [push, gcr.io/$PROJECT_ID/jacobiandotorg]

  - id: copyenv
    name: gcr.io/$PROJECT_ID/copyenv
    args: [--service, jacobiandotorg, --region, us-east1]

  - id: release
    name: gcr.io/google-appengine/exec-wrapper
    args:
      - -i
      - gcr.io/$PROJECT_ID/jacobiandotorg
      - -e
      - ENV_FILE=/workspace/.env
      - -s
      - $PROJECT_ID:us-east1:db
      - --
      - sh
      - .cloudbuild/release.sh

  - id: deploy
    name: gcr.io/cloud-builders/gcloud-slim
    args:
      [
        run,
        deploy,
        jacobiandotorg,
        --image,
        gcr.io/$PROJECT_ID/jacobiandotorg,
        --region,
        us-east1,
        --platform,
        managed,
      ]
