name: ci/cd
on: [pull_request, push]

jobs:
  # Run tests inside Docker -- this way the test environment mirrors production
  # as much as possible.
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: "build"
        run: docker-compose -f docker-compose.yaml build
      - name: "test"
        run: docker-compose -f docker-compose.yaml run web pytest

  # Deploy to gcloud run - but only if tests pass, and on push to master.
  deploy:
    needs: test
    if: github.event == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}

    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "275.0.0"
          service_account_email: ${{ secrets.GCLOUD_SA_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}

      - name: deploy
        run: |
          gcloud config set project $PROJECT_ID
          gcloud builds submit --config .cloudbuild/deploy.yaml
