name: "test with docker"

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: "build"
        run: |
          docker-compose build

      - name: "test"
        run: docker-compose run web pytest
