name: "test with docker"

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: "docker build"
        run: |
          docker build . --tag jacobiandotorg

      - name: "test"
        run: >
          docker run 
            --env DATABASE_URL=postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres 
            --env SECRET_KEY=forteststing
            jacobiandotorg:latest 
            pytest
